######################################################################
# Automatically generated by qmake (3.0) mar. mars 12 18:55:31 2019
######################################################################

TEMPLATE = app
TARGET = qtminimalCode
INCLUDEPATH += .

# Input
SOURCES += main.cpp

QT += widgets

QMAKE_CXXFLAGS += -Wall -Wextra -Wshadow

